// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngclvyolrrxwdozwffqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nY2x2eW9scnJ4d2RvendmZnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MzEwMTksImV4cCI6MjA2MjQwNzAxOX0.K0IUe0WugR476nMCfLvfYKeK1qqeXsNO5-mE0I4sYzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);